version: '3'

services:
  ollama_mistral:
    image: ubuntu:latest
    container_name: ollama_mistral
    command: /bin/bash -c "curl -fsSL https://ollama.com/install.sh | sh && ollama run mistral"
    volumes:
      - ./ollama:/root/.ollama  # Volume for saving configuration
    stdin_open: true
    tty: true
