version: '3'

services:
  ollama_mistral:
    image: ubuntu:latest
    container_name: ollama_mistral
    build: .
    volumes:
      - ./ollama:/root/.ollama  # Volume for saving configuration
    stdin_open: true
    tty: true
